# .github/actions/hello-world-action/action.yml
name: 'Hello World Action'
description: 'A custom GitHub Action that prints a message'
inputs:
  message:
    description: 'The message to print'
    required: true
    default: 'World'
runs:
  using: 'node12'
  main: 'index.js'
