# name: CI Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build_and_upload_function_code:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python environment
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8

#       # - name: Install dependencies
#       #   run: |
#       #     pip install -r requirements.txt

#       - name: Zip function code
#         run: |
#           zip -r function_app.zip function_app.py

#       - name: Upload function zip to Azure Blob Storage
#         uses: azure/azure-storage-blob-upload@v1
#         with:
#           connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
#           container-name: "function-code"
#           file-path: "function_app.zip"
#           blob-name: "function_app.zip"

      # - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      #   name: Uploading to Azure storage...
      #   with:
      #   connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      #   container-name: "function-code"
      #   source_folder: "function_app.zip"
name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_upload_function_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Azure CLI
      #   uses: azure/setup-azurecli@v2
      #   with:
      #     azcliversion: '2.27.0'  # You can use the version you need

      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Zip function code
        run: |
          zip -r function_app.zip function_app.py

      - name: Upload function zip to Azure Blob Storage
        run: |
          az storage blob upload \
            --container-name "function-code" \
            --file "function_app.zip" \
            --name "function_app.zip" \
            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
